# Generated by Django 4.1.2 on 2022-10-23 23:19

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1_total_credits', models.IntegerField(default=120)),
                ('level2_total_credits', models.IntegerField(default=120)),
                ('level3_total_credits', models.IntegerField(default=120)),
                ('level4_total_credits', models.IntegerField(default=120)),
                ('level5_total_credits', models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('moderation', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('weighting', models.IntegerField()),
                ('type', models.CharField(choices=[('A', 'Assignment'), ('E', 'Exam'), ('P', 'Project'), ('Q', 'Quiz')], default='A', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=255, null=True)),
                ('academic_year', models.PositiveIntegerField()),
                ('lecturer_comment', models.TextField(blank=True, max_length=500, null=True)),
                ('credits', models.PositiveIntegerField()),
                ('is_taught_now', models.BooleanField(default=True)),
                ('assessments', models.ManyToManyField(related_name='courses', to='general.assessment')),
            ],
            options={
                'db_table': 'course',
                'ordering': ['academic_year'],
            },
        ),
        migrations.CreateModel(
            name='DegreeClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification_name', models.CharField(max_length=255)),
                ('lower_GPA_standard', models.FloatField()),
                ('lower_GPA_discretionary', models.FloatField()),
                ('percentage_above_for_discretionary', models.IntegerField(default=50)),
                ('char_band_for_discretionary', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('GUID', models.CharField(max_length=8, unique=True)),
                ('full_name', models.CharField(max_length=225)),
                ('degree_title', models.CharField(max_length=100)),
                ('is_faster_route', models.BooleanField(default=False)),
                ('is_masters', models.BooleanField(default=False)),
                ('start_academic_year', models.IntegerField()),
                ('end_academic_year', models.IntegerField()),
                ('current_academic_year', models.IntegerField()),
                ('courses', models.ManyToManyField(related_name='students', to='general.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('preponderance', models.CharField(choices=[('NA', 'None'), ('MV', 'Medical Void'), ('CW', 'Credit Witheld'), ('CR', 'Credit Refused')], default='NA', max_length=2)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='general.assessment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='general.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='general.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('is_current', models.BooleanField(default=True)),
                ('settings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.academicyearsettings')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_head_level', models.IntegerField(choices=[(0, 'No levels'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (10, 'All levels')], default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('code', 'academic_year'), name='code_year_unique'),
        ),
    ]
