# Generated by Django 4.1.2 on 2022-11-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_name',
            field=models.CharField(default='xd', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('C', 'Coursework'), ('I', 'Individual Project'), ('G', 'Group Project'), ('E', 'Exam')], default='C', max_length=1),
        ),
    ]
