# Generated by Django 4.1.2 on 2022-10-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicYearSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1_total_credits', models.IntegerField(default=120)),
                ('level2_total_credits', models.IntegerField(default=120)),
                ('level3_total_credits', models.IntegerField(default=120)),
                ('level4_total_credits', models.IntegerField(default=120)),
                ('level5_total_credits', models.IntegerField(default=120)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='code_year_unique',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='start_year',
            new_name='academic_year',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='end_year',
            new_name='current_academic_year',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='start_year',
            new_name='end_academic_year',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer_comments',
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='general.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer_comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_academic_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('code', 'academic_year'), name='code_year_unique'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.academicyearsettings'),
        ),
    ]
