# Generated by Django 4.1.2 on 2022-10-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentresult',
            old_name='grade_mark',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
