# Generated by Django 4.1.2 on 2022-12-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_student_degree_name_alter_assessment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['current_academic_year']},
        ),
    ]
