# Generated by Django 4.1.2 on 2022-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_grade_mark_assessmentresult_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentresult',
            old_name='start_date',
            new_name='date_submitted',
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
