# Generated by Django 4.1.2 on 2022-12-09 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_student_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(default='a41f9de0-96bb-4440-aecc-444cf407972c', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='general.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='a41f9de0-96bb-4440-aecc-444cf407972c', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
