# Generated by Django 4.1.2 on 2023-01-18 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_delete_degreeclassification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lecturer_comment',
            new_name='lecturer_comment',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
