# Generated by Django 4.1.2 on 2023-01-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_rename_lecturer_comments_course_lecturer_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='added_by',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_updated',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_created',
        ),
    ]
