# Generated by Django 4.1.2 on 2023-01-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_rename_user_comment_added_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-timestamp'], name='general_com_timesta_63c872_idx'),
        ),
    ]
