# Generated by Django 4.1.2 on 2023-01-24 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='comment',
        ),
        migrations.AddField(
            model_name='assessment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='moderation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='moderation',
            field=models.IntegerField(default=0),
        ),
    ]
