# Generated by Django 4.1.2 on 2023-02-08 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_coursecomment_studentcomment_delete_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='weighting',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)]),
        ),
    ]
