# Generated by Django 4.1.2 on 2023-02-15 23:28

from django.db import migrations, models
import exam_board.tools


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_alter_academicyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='level_progression_settings',
            field=models.JSONField(default=exam_board.tools.default_level_progression_settings),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='degree_classification_settings',
            field=models.JSONField(default=exam_board.tools.default_degree_classification_settings),
        ),
        migrations.AlterField(
            model_name='levelhead',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=0),
        ),
    ]
