# Generated by Django 4.1.2 on 2023-02-28 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_academicyear_level_progression_settings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['current_level']},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='current_academic_year',
            new_name='current_level',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='moderation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-6), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
